const products = [
  {
    id: 1,
    name: "남성 푸마 X 하이록스 클라우드스펀 후디",
    engName: "M PUMA X HYROX CLOUDSPUN HOODIE",
    price: 129000,
    category: "의류",
    mainImages: ["./images/id1/main1.avif", "./images/id1/main2.avif", "./images/id1/main3.avif", "./images/id1/main4.avif", "./images/id1/main5.avif", "./images/id1/main6.avif", "./images/id1/main7.avif"],
    colorOptions: [{ img: "./images/id1/colors1.avif", name: "Gray" }, { img: "./images/id1/colors2.avif", name: "Black" }],
    intro: "전 세계 피트니스 레이스를 대표하는 HYROX와 PUMA의 기술력이 결합된 퍼포먼스 후디입니다.",
    features: ["최소 50% 이상의 재활용 소재 사용", "수분 흡·속건 기능의 dryCELL", "4-way 스트레치 슈퍼 소프트 원단"],
    material: "쉘: 78% 폴리에스터, 16% 리오셀, 6% 엘라스테인",
    careInstructions: ["인쇄부분 다림질 금지", "섬유 유연제 사용 금지", "뒤집어 세탁"]
  },
  {
    id: 2,
    name: "남성 푸마 X 하이록스 클라우드스펀 후디 (Black)",
    engName: "M PUMA X HYROX CLOUDSPUN HOODIE",
    price: 129000,
    category: "의류",
    mainImages: ["./images/id2/main1.avif", "./images/id2/main2.avif", "./images/id2/main3.avif", "./images/id2/main4.avif", "./images/id2/main5.avif", "./images/id2/main6.avif", "./images/id2/main7.avif"],
    colorOptions: [{ img: "./images/id2/colors1.avif", name: "Black" }],
    intro: "강력한 퍼포먼스를 지원하는 하이록스 컬렉션의 블랙 컬러 후디입니다.",
    features: ["클라우드스펀 소재의 부드러운 터치감", "활동성을 높이는 인체공학적 절단선"],
    material: "폴리에스터 78%, 리오셀 16%, 엘라스테인 6%",
    careInstructions: ["비슷한 색상과 세탁", "약한 세제 사용"]
  },
  {
    id: 3,
    name: "여성 푸마 X 하이록스 태드 ESS 숏 타이즈",
    engName: "W PUMA X HYROX TAD ESS SHORT TIGHT",
    price: 59000,
    category: "의류",
    mainImages: ["./images/id3/main1.avif", "./images/id3/main2.avif", "./images/id3/main3.avif", "./images/id3/main4.avif", "./images/id3/main5.avif"],
    colorOptions: [{ img: "./images/id3/colors1.avif", name: "Black" }],
    intro: "고강도 트레이닝에 최적화된 여성용 숏 타이즈입니다.",
    features: ["고신축성 소재로 근육 서포트", "허리 밴딩의 안정적인 착용감"],
    material: "나일론 및 엘라스테인 혼방",
    careInstructions: ["다림질 금지", "건조기 사용 주의"]
  },
  {
    id: 4,
    name: "남성 푸마 X 하이록스 드라이엘리트 5인치 쇼츠",
    engName: "M PUMA X HYROX DRYELITE 5\" SHORT",
    price: 79000,
    category: "의류",
    mainImages: ["./images/id4/main1.avif", "./images/id4/main2.avif", "./images/id4/main3.avif", "./images/id4/main4.avif", "./images/id4/main5.avif", "./images/id4/main6.avif", "./images/id4/main7.avif"],
    colorOptions: [{ img: "./images/id4/colors1.avif", name: "Black" }],
    intro: "레이스 데이를 위한 초경량 드라이엘리트 쇼츠입니다.",
    features: ["5인치 기장으로 최상의 가동성 확보", "드라이셀 기술로 쾌적함 유지"],
    material: "리사이클 폴리에스터 100%",
    careInstructions: ["뒤집어 세탁", "그늘에서 건조"]
  },
  {
    id: 5,
    name: "리드캣 2.0 하이록스",
    engName: "LEADCAT 2.0 HYROX",
    price: 49000,
    category: "신발",
    mainImages: ["./images/id5/main1.avif", "./images/id5/main2.avif", "./images/id5/main3.avif", "./images/id5/main4.avif", "./images/id5/main5.avif", "./images/id5/main6.avif"],
    colorOptions: [{ img: "./images/id5/colors1.avif", name: "Black" }],
    intro: "훈련 후 휴식을 위한 프리미엄 하이록스 슬라이드입니다.",
    features: ["몰딩된 풋베드의 편안한 쿠션감", "내구성이 뛰어난 아웃솔"],
    material: "인조 가죽 및 EVA",
    careInstructions: ["화기 주의", "물세척 후 건조"]
  },
  {
    id: 6,
    name: "디비에이트 나이트로 엘리트 4 푸마 X 하이록스 우먼스",
    engName: "DEVIATE NITRO ELITE 4 PUMA X HYROX WNS",
    price: 299000,
    category: "신발",
    mainImages: ["./images/id6/main1.avif", "./images/id6/main2.avif", "./images/id6/main3.avif", "./images/id6/main4.avif", "./images/id6/main5.avif", "./images/id6/main6.avif", "./images/id6/main7.avif"],
    colorOptions: [{ img: "./images/id6/colors1.avif", name: "Yellow-Black" }],
    intro: "최상의 속도를 위한 카본 플레이트 러닝화, 하이록스 스페셜 에디션입니다.",
    features: ["나이트로 엘리트 폼의 극대화된 반발력", "이노플레이트 카본 기술"],
    material: "엔지니어드 메쉬 및 고무",
    careInstructions: ["전문 세탁 권장", "고온 노출 금지"]
  },
  {
    id: 7,
    name: "레이스 데이 5 패널 캡",
    engName: "RACE DAY 5 PANEL CAP",
    price: 39000,
    category: "용품",
    mainImages: ["./images/id7/main1.avif", "./images/id7/main2.avif", "./images/id7/main3.avif", "./images/id7/main4.avif"],
    colorOptions: [{ img: "./images/id7/colors1.avif", name: "Black" }],
    intro: "운동 중 땀 흡수와 통기성이 뛰어난 5패널 레이스 캡입니다.",
    features: ["조절 가능한 후면 스트랩", "경량 기능성 원단"],
    material: "폴리에스터 100%",
    careInstructions: ["손세탁 권장", "표백제 사용 금지"]
  },
  {
    id: 8,
    name: "투 스트라이프 쿠션 양말 3P",
    engName: "TWO STRIPED CUSHION SOCKS 3P",
    price: 19000,
    category: "용품",
    mainImages: ["./images/id8/main1.avif", "./images/id8/main2.avif", "./images/id8/main3.avif", "./images/id8/main4.avif", "./images/id8/main5.avif", "./images/id8/main6.avif", "./images/id8/main7.avif"],
    colorOptions: [{ img: "./images/id8/colors1.avif", name: "White-Black" }],
    intro: "충격 흡수가 뛰어난 쿠션이 적용된 데일리 및 스포츠 양말 세트입니다.",
    features: ["아치 서포트 기능", "3켤레 1세트 구성"],
    material: "면, 폴리에스터, 엘라스테인 혼방",
    careInstructions: ["세탁기 가능", "비틀어 짜기 금지"]
  }
];